gamemode/core/sh_commands.lua
GetChar() broke the command, guess you don't need it for bodygroups.
=> fixes CharSetBodyGroup

plugins/pac.lua
It changed somewhere along the line, not sure when, or it was just never right in the first place.
=> Fix PAC3 Deserialize Call

gamemode/core/sh_commands.lua
We went public with an SSTRP Server because why the fuck not and we had this.
```The faction you provided could not be found.
[SERVER] SgtMaj. Mark Gray used command '/PlyTransfer rosser Mobile Infantry Troops'.
The faction you provided could not be found.
[SERVER] SgtMaj. Mark Gray used command '/PlyTransfer rosser Mobile Infantry Troops'.```
We fixed it on our server and it works now, so it is fully tested
=> Allows using PlyTransfer using chat

gamemode/config/sh_config.lua
`newValue` is a string, not a color. I'm guessing this was meant for the color configuration?
=> Fix error upon changing font in config.

gamemode/core/derma/cl_character.lua
The other menus work the same way. This brings the character menu in line with the others.
=> Close character menu upon pressing tab.

gamemode/core/sh_config.lua
Appears to have been missed in 93d7e8df0ad1247456b960fe9cbe98e53c084394
A cursory search for similar instances found no other matches.
=> Fix tooltips not appearing in config.

gamemode/core/derma/cl_business.lua, gamemode/core/derma/cl_character.lua, gamemode/core/derma/cl_inventory.lua, gamemode/core/derma/cl_menubutton.lua, gamemode/core/derma/cl_scoreboard.lua, gamemode/core/derma/cl_shipment.lua, gamemode/core/libs/sh_item.lua, gamemode/core/sh_config.lua
`SetToolTip` is deprecated. This changes the calls to `SetTooltip`
=> Replace deprecated tooltip calls.

entities/entities/ix_item.lua
- Fixed a typo: `itemTable.OnDestoryed` -> `itemTable.OnDestroyed`
- Renamed variable determining if the item is being destroyed: `OnBreak` sounds like an item hook.
- Passed the item entity to the `itemTable.OnRemoved` hook.
=> Refactor item entity destruction.

gamemode/core/derma/cl_charcreate.lua, gamemode/core/derma/cl_information.lua, gamemode/core/derma/cl_scoreboard.lua
On the whitelist and unwhitelist commands, as of https://github.com/NebulousCloud/helix/blob/ed4472de2b85e4017bb79908f5ff9f048d2ba8ec/gamemode/core/sh_commands.lua#L454
matches the faction with it's localized name (aka, using the L function to check if it's on the language files, or if not return the default name).
But, this is not being done on the clientside menus (like the scoreboard, character creation/selection menu) and the information menu.
=> Support localized faction names

gamemode/core/derma/cl_overrides.lua
Just what the name says, when a DermaMenu is created and it has a sub DMenu, the label doesn't get colored white and appears black.
=> Fixed AddSubMenu DMenuOption not having the right color

gamemode/core/libs/sv_database.lua
Should fix using the inventory of container inventories of props with longer path names on older mysql versions.
=> Set inventory_type to 150 length to accomodate longer path names.

plugins/typing.lua
in local servers, this is called before LocalPlayer() is valid on client
=> check if localplayer is valid

entities/weapons/ix_hands.lua
prop_physics_override and prop_physics_multiplayer are essentially identical to normal prop_physics, meaning the player should logically be able to grab them.
=> Added prop_physics derivatives to allowedHoldableClasses

entities/entities/ix_item.lua
Fixes this weird error:
```
[ERROR] gamemodes/helix/entities/entities/ix_item.lua:151: attempt to index local 'itemTable' (a nil value)
1. unknown - gamemodes/helix/entities/entities/ix_item.lua:151
```
=> Fix entities with non-existent items

plugins/vendor/sh_plugin.lua
When assigning a new description or name, pressing enter updated the vendor panel but updated the editor panel to the OLD name/desc because the DT method isn't as fast as the net lib.
Player edit name/desc -> send update to server -> server confirm and send back update to clients -> player that edited the name/desc is told to check the new name using the DT method -> dt var is outdated since the server didn't have the time to send it -> the edited name in the vendor editor panel is replaced by the OLD name
=> Vendor panel editor fix

gamemode/core/sh_commands.lua
Currently, the text shown to admins shows the new name as both the old and new, placing the broadcast first fixes that issue.
```
C17:RL.YELLOW-2 changed C17:RL.YELLOW-2's name to C17:RL.YELLOW-2.
[SERVER] C17:RL.YELLOW-2 used command '/CharSetName C17:RL.YELLOW-1 C17:RL.YELLOW-2'.
```
This should be
```
C17:RL.YELLOW-1 changed C17:RL.YELLOW-1's name to C17:RL.YELLOW-2.
[SERVER] C17:RL.YELLOW-1 used command '/CharSetName C17:RL.YELLOW-1 C17:RL.YELLOW-2'.
```
=> Fix admin notification to show correct oldname

plugins/persistence.lua
For example, if you have a persistent entity, and you remove the addon it's from, `ents.Create` would fail and the plugin would run calls on a null entity and break everything.
=> Fix persistence breaking LoadData chain if entity could not be created.

gamemode/core/sh_util.lua
`include` returns whatever the specified script returns. `ix.util.Include` should also support this behavior.
https://wiki.garrysmod.com/page/Global/include
=> Add return values for ix.util.Include

gamemode/core/sh_commands.lua
Recursive nature of the client:RequestString() caused the notification to appear twice.
Old:
```
Gary changed Gary's name to .
[SERVER] Gary used command '/CharSetName gary'.
Gary changed Gary's name to Johnny.
[SERVER] Johnny used command '/CharSetName Gary Johnny'.
```
New:
```
[SERVER] Johnny used command '/CharSetName johnny'.
Johnny changed Johnny's name to Jacob.
[SERVER] Jacob used command '/CharSetName Johnny Jacob'.
```
=> Removed duplicated notification on /charsetname panel

gamemode/core/meta/sh_item.lua
This is useful if targetInv is a bag inventory
Instead of changing item.invID back to what was initially passed with ITEM:Transfer() we'll just let the targetInv:Add function set the invID. Setting the invID after targetInv:Add will not work if targetInv was not the same inventory as the invID passed with ITEM:Transfer().
=> ITEM:Transfer doesn't need to set item's inventory ID

gamemode/core/meta/sh_player.lua, gamemode/items/base/sh_weapons.lua
Couple of changes in here to make ragdolling more consistent in terms of the player's equipped weapons.
The main change leverages the weapon's base equip & unequip code to consistently store equipped item weapons (including the loaded clip). Any extensions made in custom weapon bases using ITEM.OnEquipWeapon & ITEM.OnUnequipWeapon to store additional information etc. will also be properly called. This also removes the need to write extra code to make ragdolling consistent, only equipping and unequipping needs to be made consistent.
As the item will be unequipped, it can be moved out of the player's inventory while he is ragdolled. An additional check is added to see if the weapon is still in the same inventory to know if it should be re-equipped.
For non-item based weapons, the clip is …
=> Weapon consistency when ragdolling

gamemode/core/libs/sh_chatbox.lua
Currently there is no way to change the range after the chat class has been created as the local 'range' variable is used in the function, rather than data.range.
=> CanHear range properly uses data.range

gamemode/core/sh_util.lua
The roles for the `a` and `b` variables are actually reversed.
=> Fix ix.util.StringMatches documentation error.

gamemode/core/libs/sh_language.lua
"L" function now returns the English phrase if the phrase in the requested language could not be found.
An meaningful example would be the Area plugin, as it contains untranslated phrases.
As you can see in the image below, if the user is using a language other than English, the "keys" will appear instead of a more descriptive text.
The next image shows how it would look with the fix applied and without the user needing to change his language.
=> "L" function now returns sensible values.

gamemode/core/derma/cl_overrides.lua
DComboBox will go off screen if there are too many elements, meaning some elements are not accessible. This stops it the bottom of the screen.
=> Prevent DComboBox from going off screen,

gamemode/core/derma/cl_generic.lua
It is very wonky because the size changes all the time if you don't do it like this and it makes using sliders with decimal points a pain.
Before:
After:
=> Format slider lib to number of decimal places

plugins/persistence.lua
* Fix persistence plugin not saving the model of prop_effect entities.
* Improve log information by displaying the model instead of the entity itself.
=> Fix issue with persistence and prop_effect models

plugins/vendor/sh_plugin.lua
When changing buy/sell, sell only, buy only, price, stock it would set it one column to the left of what it should be.
=> Fix updated vendor edit info in wrong columns

gamemode/core/libs/sh_command.lua
If we putting command arguments inside quation marks, for example, using "/TextAdd" command, then it counts every single UTF-8 character inside as 2 characters. This pull request aims to fix this respectively.
Before:
After:
=> Fix ExtractArgs counting UTF-8 chars incorrectly under certain circumstances

gamemode/core/derma/cl_generic.lua
=> Use utf8 functions on GetContentSize and DrawKernedText

gamemode/core/meta/sh_inventory.lua
While documenting the Inventory meta I discovered a lazy variable check within `meta/sh_inventory.lua`  that causes it to lazily search if `id` is present within the bag item's data. Seeing as id is a very common word to use for small index searches, this will prevent any mismatches for anything that isn't a bag.
=> Fix issue where GetBags could very easily return non-bags.

gamemode/core/meta/sh_inventory.lua
Despite noSave being a very useful variable for creating easily manipulatable single use inventories, it has no documentation or official way to set the variable, this will add helper functions and document the existence of the variable as a whole.
=> Add and Document Get/Set ShouldSave functions for Inventories.

gamemode/core/libs/sh_character.lua
This will allow minNameLength to be lowered beyond the default 4 if one so chooses. I do not understand why this check was not in place before, I would think it obvious to ensure a value actually exists before trying to perform operations on the value.
=> Check to make sure player actually entered a name

plugins/containers/sh_plugin.lua
The key to access on the ix.container.stored table hasn't always had the :lower() method which leads to problems with container models which have capital characters in their path.
=> Added missing :lower() invokes

gamemode/core/hooks/cl_hooks.lua
`ix.hud.DrawDeath` function is being drawn in [PostDrawHUD](https://wiki.facepunch.com/gmod/GM:PostDrawHUD) hook, wich has literally the same issue with drawing anything in it as [PreDrawHUD](https://wiki.facepunch.com/gmod/GM:PreDrawHUD) has.
This 2 lines of code make this:
Look like this:
=> Fix death screen not drawing text properly

docs/manual/getting-started.md
From the MySQLOO page: 
> Previously you were required to place libmysqlclient.dll besides your srcds executable. This is not required anymore since MySQLOO now links statically against libmysqlclient.
=> update docs to specify newer versions of mysqloo dont require libmysql.dll

gamemode/core/derma/cl_generic.lua
Fixed IxIconTextEntry being locked to just "V", the 'search icon'. Added 2px spacing to the right of the icon for it to looked more "centered.". I encountered this issue while trying to stylize some text entry boxes, and had to override the panel with literally just a couple lines.
You can preview all of the icons that exist in `IxSmallTitleIcons` by using the following concommand:
```
concommand.Add('ix_iconpreview', function(ply, _, args)
local ui = vgui.Create('DFrame')
ui:SetSize(600, 600)
ui:Center()
local n = ui:Add('DScrollPanel')
n:Dock(FILL)
for i=32, 256 do
local x = n:Add('ixIconTextEntry')
x:Dock(TOP)
x:SetIcon(utf8.char(i))
x:SetText(utf8.char(i))
end
end)
```
I was originally also going to update it so that it could have it's Icon Font set manually to the medium/big ones, …
=> Update IxIconTextEntry to not use hardcoded Icon, adjust style of IxIconTextEntry.

gamemode/core/cl_skin.lua
gamemodes/helix/gamemode/core/cl_skin.lua:229: attempt to index a nil value 
was the error before that fix, the code that I was using was taken from https://wiki.facepunch.com/gmod/Panel:Receiver
=> Fix error related to Drag'n'Drop support

gamemode/core/libs/sh_notice.lua
Before it would error about missing a data table, it's been resolved the same way it works above in ix.util.Notify()
=> Fix LocalPlayer():ChatNotify() and LocalPlayer():ChatNotifyLocalized()

gamemode/core/libs/sh_notice.lua
Makes it so you can have send Error messages to client.ChatNotify and client.ChatNotifyLocalized
=> Fix a problem with client.ChatNotify and client.ChatNotifyLocalized serverside

plugins/typing.lua
Literally the same is being checked here:
https://github.com/NebulousCloud/helix/blob/016b0673ff72b4f76d810fe47495f34d986ae446/plugins/typing.lua#L128
=> Remove redundant check in typing plugin

gamemode/core/derma/cl_character.lua
Only `bUsingCharacter` variable determines what will happen on return button click. And so, this PR aims to make `UpdateReturnButton` function change `bUsingCharacter`.
=> Prevent players from returning to the kicked or banned character via return button

docs/hooks/plugin.lua
Just a small correction to the hook documentation, CharacterLoaded gets called on both the client and the server.
```lua
function PLUGIN:CharacterLoaded(character)
print(character)
end
```
=> Fix CharacterLoaded realm documentation

gamemode/core/libs/sv_database.lua
Currently every Row in ix_schema table is updated, this causes issues if you have more than the default one 'ix_characters' row. As updating every row then next restart adds unnecessary columns to each table. Doing a simple 'Where' clause fixes this issue.
Before Fix:
https://i.imgur.com/Q6OB3KN.png
After Fix:
https://i.imgur.com/kgDHzGA.png
=> Fix issue with 'ix_schema' table.

docs/hooks/plugin.lua, gamemode/core/hooks/sv_hooks.lua, gamemode/items/base/sh_bags.lua
Currently combine item does not check if the player owns the second item, this is a very big problem.
This will fix it by checking if the player has access to the inventory containing the second item.
Also adds hook `CanPlayerCombineItem` and documentation.
=> Add CanPlayerCombineItem hook

gamemode/core/libs/sh_item.lua, gamemode/core/sh_util.lua
[`table.Merge`](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/table.lua#L81-L95) function's merging is if element is table, replacing table's element.
```lua
function table.Merge( dest, source )
for k, v in pairs( source ) do
if ( istable( v ) && istable( dest[ k ] ) ) then
-- don't overwrite one table with another
-- instead merge them recurisvely
table.Merge( dest[ k ], v )
else
dest[ k ] = v
end
end
return dest
end
```
Unfortunately, `table.Merge` function is not include metatable object case. (metatable is kind of table.) This means that the metatable reference of the table's metatable object does not change, only the value of the object changes.
Therefore, the following problem occurs when the gamemode is refreshed.
```lua
for _, v in …
```
=> Fix item instance's metatable object reference is not updated when gamemode refreshed.

plugins/vendor/sh_plugin.lua
`[LOG] Citizen Character purchased a '.45 ACP Rounds' from the 'John Doe' vendor for 0 tokens.`
`[LOG] Citizen Character sold a '.45 ACP Rounds' to the 'John Doe' vendor for 0 tokens.`
=> Add logging for vendor trades

gamemode/core/derma/cl_config.lua, gamemode/core/libs/sh_plugin.lua, gamemode/core/sh_config.lua
Just a few minor fixes/bits of polish
- Updated the checkbox text to be consistent between the loaded and unloaded lists (ON/OFF instead of YES/NO for the unloaded list)
- Unloaded plugins that are queued for loading no longer disappear from the unloaded list
- Autorefresh no longer breaks the unloaded plugins list on the client
The ix.plugin.unloaded list changes don't impact how they're stored in data as that's handled separately.
=> Improve plugin config UI

gamemode/shared.lua
This pull request is basically inherited from #321, but this time this function will always return a value whatever the situation (even in a `-multirun` environment) since yesterday's last update:
- https://store.steampowered.com/news/app/4000/view/3664293140704541926
- https://wiki.facepunch.com/gmod/Player:SteamID64~diff:551389
- https://wiki.facepunch.com/gmod/Player:AccountID~diff:551390
I did some testing with these changes and didn't see any issues as everything is now done internally by Garry's Mod, so it's pretty much a transparent change.
=> Remove the SteamID64 workaround

gamemode/core/libs/sh_command.lua, gamemode/languages/sh_english.lua
Adds a clientside concommand for `ix` to handle basic autocompletion
Something to note is that because we can't have both clientside command/autofill and serverside execution this'll route every command through `ix.command.Send`, causing them to be affected by the ixNextCmd cooldown whereas direct `ix` commands weren't previously.
=> Clientside autocomplete for ix concommands

gamemode/core/derma/cl_character.lua
Sometimes IGModAudioChannel can be NULL so this can cause errors and bugs.
=> Add IsValid check to a NULL IGModAudioChannel

gamemode/core/libs/sh_item.lua
Items that aren't bases which have a base, will have isBase set because isBase will be `nil` unless specified otherwise.
With this I make sure they receive a value, which would be false, which is different than nil therefore it won't get set in derived items.
https://github.com/NebulousCloud/helix/blob/c711869b471f843f6138ac4d0545d9773c7e5c00/gamemode/core/libs/sh_item.lua#L188
This is the line which sets item properties if they're nil.
=> Fix problem with derived items having isBase true

plugins/vendor/sh_plugin.lua
The essence of the exploit is that you can buy those things that have the “Buy Only” status.
=> Vendor buy net validation

gamemode/config/sh_config.lua, gamemode/core/hooks/sv_hooks.lua, gamemode/core/libs/sh_chatbox.lua, gamemode/core/libs/sh_class.lua, gamemode/core/meta/sh_character.lua, gamemode/core/meta/sh_entity.lua, gamemode/core/meta/sh_inventory.lua, gamemode/core/meta/sh_item.lua, gamemode/core/sh_commands.lua, gamemode/core/sh_util.lua, plugins/area/sv_hooks.lua, plugins/doors/derma/cl_door.lua, plugins/doors/sv_plugin.lua, plugins/observer.lua, plugins/pac.lua, plugins/recognition.lua, plugins/typing.lua
Replace all ents.GetAll and player.GetAll to ents.Iterator and player.Iterator for performance reasons
=> Replace ents.GetAll and player.GetAll

gamemode/core/sh_util.lua
The ix.util.FindPlayer() function previously returned an unexpected result when run with an empty string as the identifier; now it reacts the same way it would if it did not find any player.
=> Refactor FindPlayer() to handle empty identifier.

docs/hooks/plugin.lua, plugins/vendor/entities/entities/ix_vendor.lua
I feel like some players may want to add variables to vendors, which can prevent accessing the vendor. This will likely not be used a lot, but I feel like it would be worth having.
=> Added Vendor Argument to CanPlayerUseVendor

gamemode/core/derma/cl_config.lua
Populate function required for array type setting rows was missing from the population function for ixConfigManager, which resulted in an empty options array for the ComboBox element.
=> Fixed config derma not working with array settings

gamemode/core/hooks/sh_hooks.lua
In the CanPlayerUseCharacter hook, there is a check to make sure the character isnt banned. If the character received a temporary ban at some point and that ban runs out, the check in that function calls return, if the ban isnt valid anymore, preventing later checks from happening, which could for instance let a whitelist character load, as the whitelist check would not happen.
=> Fixed previous character ban preventing later checks from happening

gamemode/items/ammo/sh_crossbowammo.txt
For some reason, the default model is set to BoxBuckshot.mdl when CrossbowRounds.mdl exists. This change will save a whopping five seconds of time at most.
=> Swap sh_crossbowammo.txt model

plugins/area/derma/cl_areaedit.lua
Only derma changes, spanish support is not include in this pull request.
Before the edit: ![image](https://github.com/user-attachments/assets/e6c53941-fb76-4ac8-a88c-f694113ead56)
After the edit: ![image](https://github.com/user-attachments/assets/ae384600-7942-4be0-9765-6d67913faa02)
=> Improvement of the /AreaEdit derma

plugins/vendor/entities/entities/ix_vendor.lua, plugins/vendor/sh_plugin.lua
Calling `PhysicsInit` while trying to create `PhysicsObject` ends with it having invalid AABB if model is `prop_ragdoll`, despite the entity itself having the valid ones. The result is simple - weird behaviour of vendors when they are being unfreezed and, for example, being knocked over.
The way to fix it is to use `PhysicsInitBox` instead of `PhysicsInit`, which adds another issue with bounding boxes being to big ignore the fact that they are remaining same even if entities angle is being changed. For example, you can just bump into invisible collision if vendor is 'lying' on a ground.
And this is where `AddCallback` and `OnAngleChange` come in, providing ability to change vendors collision bounds when angles is being changed.
As addition I want to mention, that currently, after changing …
=> Improvments to vendors PhysicsObjects and their collision

plugins/chatbox/derma/cl_chatbox.lua, plugins/chatbox/derma/cl_chatboxcustomize.lua
This adds some missing logic for handling chatbox tab renaming. Helix would produce an unexpected 'This tab already exists' error when renaming a chat tab. When that issue is fixed, the tab is still not properly renamed due to mismatched IDs, and the active tab variable is not updated to point to the new ID, causing an error.
=> Chatbox Tab renaming fixes.

gamemode/core/libs/sv_networking.lua
This fixes an issue with global variables when a table is networked.
The problem is that if a table that is a global variable is changed in any way, because tables in Lua are references, the table will also change in `ix.net.globals`, meaning that the check on line 41 would essentially be comparing the table with itself, which would always return true, and thus never actually be networked.
This adds an exception for tables to make them always pass that check, in order to be properly networked.
=> Allow global table vars to always be networked.

plugins/stamina/sh_plugin.lua
We should not be forcing the speed of anything in a temporary manner, especially reverting back to config values when these may not be the values that were being used.
Credits to @WardenPotato for explaining this to me and offering a solution when I ran into issues with this exact behavior.
=> stamina: Move speed reduction to a SetupMove

gamemode/config/sh_options.lua, gamemode/core/derma/cl_menu.lua, gamemode/languages/sh_english.lua
New option that lets you automatically close the game UI when exiting the tab menu with escape. Defaults to off to avoid changing established behavior.
=> escCloseMenu option

gamemode/core/libs/sh_option.lua
https://docs.gethelix.co/libraries/ix.option/#OptionStructure states you can set the phrase and description via the OptionStructure. This allows that functionality, so you don't need to define it within a language file. Testing yielded positive results.
=> Add phrase and description in ix.option.Add()

gamemode/core/meta/sh_item.lua
Account for characters, such as NPC's, who have a character but not an inventory, this causes an index nil error.
=> Account for characters without an inventory

gamemode/config/sh_config.lua, gamemode/core/hooks/cl_hooks.lua, gamemode/core/hooks/sh_hooks.lua
https://github.com/user-attachments/assets/46a4ebc7-3acc-4be7-afae-58e0a957af0c
=> Add option to disable business in config

gamemode/core/derma/cl_attribute.lua
change the bar fill speed to a variable instead of magic number
sometimes it's too slow or fast for our needs, just set pnl.animateSpeed to something higher or lower
=> ixAttributeBar animate speed param

gamemode/core/meta/sh_item.lua
In the [Item meta function "Remove"](https://github.com/NebulousCloud/helix/blob/418947abce83519416fe6cc0fd9ec0934a37e742/gamemode/core/meta/sh_item.lua#L418-L497) there is some code that runs if the previous loop [(Line 424-436)](https://github.com/NebulousCloud/helix/blob/418947abce83519416fe6cc0fd9ec0934a37e742/gamemode/core/meta/sh_item.lua#L424-L436) couldn't find the to-be-deleted item in all the slots, that its expected to be at. E.g. an item with x = 1, y = 3, w = 2, h = 1, should be in the slots, x = 1 & y = 3; x = 2 & y = 3. If, for example, the item object is not in x = 2 & y = 3, this "fallback" code is run: https://github.com/NebulousCloud/helix/blob/418947abce83519416fe6cc0fd9ec0934a37e742/gamemode/core/meta/sh_item.lua#L438-L455
However, the current fallback code doesn't …
=> Changed ITEM:Remove() fallback code to work and (hopefully) be more reliable

gamemode/core/libs/sh_plugin.lua
Accidentally closed this PR.
The change would set the global variable "PLUGIN" to the local variable oldPlugin after a plugin is loaded to allow plugins inside plugins. This change does not result in the PLUGIN global variable staying even after all plugins have been defined. See below for a detailed step by step analysis as to why.
Firstly a new plugin is loaded using ipL. For this explanation, let's say that this is the first plugin that is loaded overall and that it has one or multiple plugins in its plugins folder. So this is what the directory looks like plugin/plugins/nested_plugin.
At this line: https://github.com/NebulousCloud/helix/blob/8cab35ebacdd244981226a3f3c5d8480fd430d12/gamemode/core/libs/sh_plugin.lua#L17
the local variable "oldPlugin" is set to the gv (global variable) …
=> Fixed plugins inside plugins (Repost)

gamemode/core/meta/sh_player.lua
The comment above states that the `default` argument is optional, but trying not to pass it into the function call throws an error because `net.WriteString` cannot pass `nil`.
=> fixed a possible error in `RequestString`.

gamemode/core/libs/sh_log.lua
```lua
Error: gamemodes/helix/gamemode/core/libs/sh_log.lua:115: bad argument #1 to 'WriteString' (string expected, got nil)
[C]:-1 - WriteString()
gamemodes/helix/gamemode/core/libs/sh_log.lua:115 - Send()
gamemodes/helix/gamemode/core/libs/sh_log.lua:105 - callback()
addons/sam-153/lua/sam/modules/cami.lua:304 - onResult()
addons/sam-153/lua/sam/modules/cami.lua:309 - callback()
addons/sam-153/lua/sam/modules/support_cami.lua:122 - v()
lua/includes/modules/hook.lua:96 - Call()
addons/sam-153/lua/sam/modules/cami.lua:269 - PlayerHasAccess()
addons/sam-153/lua/sam/modules/cami.lua:308 - GetPlayersWithAccess()
gamemodes/helix/gamemode/core/libs/sh_log.lua:104 - Add()
gamemodes/helix/gamemode/core/libs/sh_command.lua:519 - Run()
gamemodes/helix/gamemode/core/libs/sh_command.lua:561 - …
```
=> Fallback ix.log.Parse() Invalid Type

gamemode/core/libs/sh_character.lua
The max value for the attribute bar should match the maxValue variable that is set when defining an attribute instead of the overall attribute maximum.
=> Fixed issue with attribute bar not being max value

gamemode/core/meta/sh_inventory.lua
In `meta/sh_inventory.lua` to be added items have their slots reserved with a `true` value:
https://github.com/NebulousCloud/helix/blob/e5bc1e0be29848feb9b890f5affce59fd72071fd/gamemode/core/meta/sh_inventory.lua#L891
After this reservation an item instance will be created by `ix.item.Instance`, which may take some time, since it is in a query callback:
https://github.com/NebulousCloud/helix/blob/e5bc1e0be29848feb9b890f5affce59fd72071fd/gamemode/core/libs/sh_item.lua#L78-L96
Only once the query callback calls back with the fully instanced item, is the reserved `true` value replaced with the item.
https://github.com/NebulousCloud/helix/blob/e5bc1e0be29848feb9b890f5affce59fd72071fd/gamemode/core/meta/sh_inventory.lua#L907-L916
This commit excludes these mentioned `true` values when using …
=> Fix inventory Iter returning non-item true values for not fully-instanced items

gamemode/core/meta/sh_item.lua
InventoryItemRemoved is a hook called when an item is removed via the INVENTORY:Remove() meta function on the server. Weirdly, the hook is NOT called when ITEM:Remove() is called on the server, despite the same "ixInventoryRemove" net message going out in both cases when the inventory exists.
This brings parity to both meta functions - when an item instance is removed directly from an inventory or self deleted when inside of a client's inventory, the hook will be called as is seemingly intended. This will only happen if the item is not being transferred, is inside of a client's inventory, and should be deleted.
=> Enable InventoryItemRemoved call for ITEM:Remove()

gamemode/core/cl_skin.lua
Fixed the Helix derma skin causing an error when using `DHScrollBar`.
Both `DVScrollBar` (Vertical) and `DHScrollBar` (Horizontal) call the `PaintScrollBarGrip` skin hook (through their **child** `DScrollBarGrip`). However currently in Helix the `PaintScrollBarGrip` skin hook expects `btnUp` and `btnDown` to exist on the **parent** (See changed files). This fails because `DHScrollBar` has `btnLeft` and `btnRight`, meaning without this PR its not possible to use `DHScrollBar` on a panel using the Helix skin. 
Besides this fix I added a few empty paint hooks to style the horizontal bar the same way as vertical bars are in Helix:
This shouldn't break anything and looking at the gmod source code [it doesn't seem `DScrollBarGrip` is used anywhere …
=> Fix error with DHScrollBar in Derma skin and add support for it

gamemode/core/meta/sh_player.lua
In Helix the `playerMeta:PerformInteraction` function is only used in `ENT:Use`. `ENT:Use` internally resol `Player:GetUseEntity` to test which entity is being used, which does not neccessarily have to be exactly under the crosshair. 
Before this commit, the exact trace performed did not necessarily land on the same entity being used, meaning you could press USE to pickup an item and after the delay nothing would happen.
`PerformInteraction` is exclusively used in `ENT:Use` for these entities (which are thus the only internal ones affected by this PR):
* `ix_item`
* `ix_money`
* `ix_shipment`
This gif shows me pressing USE (e) on the entity, initiating the interaction. However because I'm slightly off, the trace in the current code doesn't register this as successful. As I move the …
=> Fix PerformInteraction initiating action, but not finishing it, due to inconsistent tracing

gamemode/core/libs/sh_class.lua
A break statement was added after detecting a duplicate uniqueID in the class loading loop to prevent unnecessary iterations.
This pull request makes a minor fix to the `ix.class.LoadFromDir` function in `gamemode/core/libs/sh_class.lua` by adding a `break` statement after setting the `halt` flag. This ensures the loop stops immediately once a matching `uniqueID` is found, improving efficiency.
=> Add missing break in class loading loop

docs/hooks/plugin.lua, gamemode/core/hooks/sv_hooks.lua, gamemode/core/libs/sh_menu.lua
As discussed in: https://github.com/NebulousCloud/helix/pull/483#issuecomment-3228560091
> [...] I suggest that instead of just a configuration option a default `CanPlayerInteractEntity` hook implementation should do the range check, e.g: in `helix/gamemode/core/hooks/sv_hooks.lua`:
> 
> ```lua
> function GM:CanPlayerInteractEntity(client, entity, option, data)
>   return entity:GetPos():Distance(client:GetPos()) <= 96
> end
> ```
> 
> Or with the configuration proposed in this PR:
> 
> ```lua
> function GM:CanPlayerInteractEntity(client, entity, option, data)
>   local configDistanceSqr = ix.config.Get("interactionRange", 96) ^ 2
>   return entity:GetPos():DistToSqr(client:GetPos()) <= configDistanceSqr
> end
> ```
> 
> That way schemas and plugins can force specific entities to be …
=> Have base CanPlayerInteractEntity hook handle interact range check to allow plugin override

gamemode/core/hooks/sv_hooks.lua
Refines the logic for selecting a model when spawning a bot character. Ensures the selected model is a valid string and defaults to 'models/gman.mdl' if not, improving reliability and preventing errors with invalid model types.
This pull request updates the player initialization logic to make the selection of a character model more robust and error-resistant. The main improvement is a safer process for choosing a model for new players, ensuring that the selected model is always a valid string and providing a fallback if necessary.
**Player model selection improvements:**
* Refactored the model selection in `GM:PlayerInitialSpawn` to explicitly choose a random model from the list returned by `faction:GetModels(client)`, handle cases where the model is a table (by selecting the first …
=> Improve model selection for bot character spawn
