NebulousCloud/helix

- gamemode/items/base/sh_weapons.lua
- plugins/vendor/sh_plugin.lua
Encountered these two issues while making a different vendor entity and a wipe inventory command for development.
> Fix Weapons not removing properly from Inventories, Fix vendor selling function.

- plugins/logging.lua
Changes (timed out) to (Timed out) b/c it bugged me
SteamID's are added to DC's and connections to catch people who DC to avoid shit
> Fixes grammar on timeout + adds steamID to disconnect

- gamemode/core/libs/sh_log.lua
Fixes another part of #24 missed by commit 30a7e8f205c917b8f6301caf6f3110e8438aef01
Tested and works in-game.
> Fixes another error with logging if the log type doesn't exist

- gamemode/core/hooks/cl_hooks.lua
The current chat messages are too thin and difficult to read.
This improves the readability of the messages.
> Improve chatbox readability.

- plugins/vendor/sh_plugin.lua
This fixes #34 where a server error occurs upon using a vendor.
> Fix server error upon using vendors.

- gamemode/core/sh_commands.lua
Fixes this: https://github.com/NebulousCloud/helix/pull/22
As well as the fact that it just makes everyone's lives easier. Tested and functional.
> Make some commands' parameters optional

- plugins/containers/sh_plugin.lua
For bug: Containers are saving with index 0 if callback not answer in time.
> Fix for containers

- .luacheckrc
- gamemode/core/derma/cl_help.lua
- gamemode/core/hooks/sv_hooks.lua
- gamemode/core/libs/sh_chatbox.lua
- gamemode/core/libs/sh_command.lua
- gamemode/core/libs/sh_log.lua
- gamemode/core/libs/thirdparty/sh_cami.lua
- gamemode/core/sh_commands.lua
- gamemode/core/sh_config.lua
- gamemode/core/sh_util.lua
- plugins/3dpanel.lua
- plugins/area/sv_hooks.lua
- plugins/doors/sh_commands.lua
- plugins/mapscene.lua
- plugins/observer.lua
- plugins/pac.lua
- plugins/spawns.lua
- plugins/vendor/entities/entities/ix_vendor.lua
- plugins/vendor/sh_plugin.lua
This will leverage the permission system of any installed admin mods that implement CAMI
> Make command access customizable

- gamemode/core/cl_skin.lua
Sorry about dirty pull request log. I'm going to have to fix the habit...
> Implementing SetBackgroundColor method function.

- entities/weapons/ix_hands.lua
- gamemode/config/sh_config.lua
- plugins/stamina/sh_plugin.lua
The anim was fuckedup because of playbackrate being changed by the hook think before the anim finished playing
I also plan to move the stamina related configs to the plugin, not sure when it has to be executed.
> Fixed hands (anim and if there is no stamina plugin)

- gamemode/languages/sh_english.lua
Ran into it a couple of times, seems to have been removed long ago from this file.
Exists in
https://github.com/NebulousCloud/helix/blob/master/gamemode/items/base/sh_weapons.lua#L131
https://github.com/NebulousCloud/helix/blob/master/plugins/vendor/sh_plugin.lua#L361
> Add the missing tellAdmin localization

- gamemode/core/hooks/cl_hooks.lua
> player ToolTip on player ragdolls

- gamemode/core/libs/sv_networking.lua
- gamemode/core/libs/thirdparty/sh_date.lua
- gamemode/core/libs/thirdparty/sh_tween.lua
- gamemode/core/libs/thirdparty/sh_utf8.lua
- gamemode/core/libs/thirdparty/sh_yaml.lua
It's mostly micro-optimization but going from `type(fn) == "function"` to `isfunction(fn)` is ~40% faster
> micro-optimization on type() calls

- gamemode/core/libs/sv_networking.lua
- gamemode/core/libs/thirdparty/sh_date.lua
- gamemode/core/libs/thirdparty/sh_tween.lua
- gamemode/core/libs/thirdparty/sh_utf8.lua
- gamemode/core/libs/thirdparty/sh_yaml.lua
#137 but without the lil mistake
> Type optimization (Fixed this time)

- gamemode/core/derma/cl_charcreate.lua
- gamemode/core/derma/cl_charload.lua
Checks for aspect ratios over 16:9 and raises FOVs to fit models on screen.
> Added support for ultrawide resolutions

- plugins/recognition.lua
2 bits only allowed for 0-3 when recognition was sending 4, causing it to never work.
> Fixed yell range of recognition

- gamemode/items/base/sh_weapons.lua
> Run OnEquipWeapon when loadout is given.

- entities/weapons/ix_hands.lua
I created this request cause' I had a problem with setting custom hands to some factions. The thing is - the custom hands were not from GMod, they were installed as the addon.
> Fixing ix_hands setting non-standard c_hands in t_pose

- gamemode/core/derma/cl_charcreate.lua
Fixes more than one faction being selected in the faction select screen when making a new character.
> Fix more than one faction being selected

- docs/hooks/plugin.lua
- gamemode/core/sh_commands.lua
Adds a hook that fires when a player has gotten up from the ground.
> Add OnCharacterGetup hook

- gamemode/languages/sh_english.lua
- plugins/vendor/derma/cl_vendoreditor.lua
> Add Vendor Searchbar & Categories

- gamemode/core/libs/sh_currency.lua
So you can use ix.currency.Set() directly.
> Add ix.currency.model arg for ix.currency.Set.

- plugins/3dpanel.lua
- plugins/3dtext.lua
Extra optional brightness argument clamped to 0 - 100
Fixed an error related with deleting multiple panels not removing for the client
> Added panel brightness argument and fixed deleted panel staying bug

- docs/hooks/plugin.lua
- gamemode/core/derma/cl_modelpanel.lua
- Added PostDrawModel function from DModelPanel
- Added PostHelixModelView hook
If something should be changed eg use a hook instead of a function please change, but to have no option to render something after the main model has been drawn was an annoying discovery for me when helping someone.
> Adding some extra functionality to ixModelPanel

- gamemode/core/meta/sh_inventory.lua
In the first round of my documentation sweeps, I bring to you, the inventory meta library, documented with all functions, intended and internal exposed to the documentation library, this should cut down on a few questions in \#support about some lib functions that previously weren't documented.
> Overhaul Documention of Inventory Class/Meta Functions.

- gamemode/core/derma/cl_dev_icon.lua
- gamemode/languages/sh_english.lua
Using the fl icon editor as a base, this allows functionality using a DAdjustableModelPanel instead of having to work with archaic DNumberWangs.
> Update the Icon Editor

- gamemode/core/cl_skin.lua
- gamemode/core/derma/cl_deathscreen.lua
- gamemode/core/hooks/cl_hooks.lua
- gamemode/core/hooks/sv_hooks.lua
- gamemode/core/libs/cl_hud.lua
Timings are not exactly the same.
> Move Death Screen to Panel

- gamemode/core/derma/cl_deathscreen.lua
- gamemode/core/hooks/cl_hooks.lua
Fix Admin Respawning not Closing Death Screen
> Fix not Drawing Pickup Circle

- gamemode/core/hooks/cl_hooks.lua
This pissed me off to end.
without fix: https://i.imgur.com/CsqzlLD.png
with fix: https://i.imgur.com/anul3rV.png
> Fix missing information tab blur

- gamemode/core/meta/sh_inventory.lua
Took this from this merged [PR](https://github.com/NebulousCloud/helix/pull/316).
> Make isBag variable in GetItems function more reliable

- plugins/mapscene.lua
Currently paired map scenes are being stored with the position set as key in the scenes table, this leads to them not saving.
> Fix paired scenes not saving.

- gamemode/core/sh_util.lua
> Replace Distance by DistToSqr

- gamemode/core/sh_util.lua
> Fixed a gap on a first line for a wrapped text

- gamemode/core/libs/sh_item.lua
Fixes being able to take items from inventories at any distance, and unauthorized inventory access.
> Fix inventory move logic

- gamemode/core/meta/sh_inventory.lua
a best way to iterate inventory items
usage:
```lua
for item, x, y in inventory:iter() do
...
end
```
im not sure how to document iterator returns (im not familiar with LDoc) 
I think it should be something like:
```lua
-- @treturn item item
-- @treturn number The `x` coordinate of item
-- @treturn number The `y` coordinate of item
```
but idk where to put it
> Added ix.meta.inventory:iter()

- docs/hooks/plugin.lua
https://github.com/NebulousCloud/helix/blob/cf3c8a29b5aa03ca3610292095258b7a246a9a65/gamemode/core/hooks/sv_hooks.lua#L712
> Update realm of hook

- gamemode/core/hooks/cl_hooks.lua
Call IsError instead of comparing IMaterial with string
> Fix hasVignetteMaterial always returning true

- plugins/containers/entities/entities/ix_container.lua
Added a call for OnOpen and OnClose in order to make containers interactions more customizable.
> Added OnOpen and OnClose params for container

- gamemode/core/libs/thirdparty/sh_cami.lua
It does not contain any modifications of its own; it only updates CAMI to the latest version.
I saw that SAM addon and DarkRP recently updated CAMI and I wanted to update Helix.
> Updated CAMI to latest version.

- gamemode/core/libs/sv_player.lua
Don't save bots data as this can cause a Lua error and is a bit useless
> Don't save bots data

- gamemode/items/base/sh_outfit.lua
When you equip or unequip armor hands will changing without any problems just thx self:GetOwner():SetupHands()
> Hands changing

- plugins/doors/cl_plugin.lua
- plugins/doors/sh_plugin.lua
https://github.com/user-attachments/assets/0f5b5f5a-1ff0-4fe2-8f91-5cb21c31831a
> Fix Lua error that occurs upon selling the door

- gamemode/core/derma/cl_inventory.lua
- gamemode/core/hooks/sh_hooks.lua
- gamemode/core/hooks/sv_hooks.lua
- gamemode/core/libs/sh_storage.lua
- gamemode/core/meta/sh_inventory.lua
- gamemode/core/meta/sh_item.lua
- gamemode/items/base/sh_bags.lua
- gamemode/items/base/sh_outfit.lua
- gamemode/items/base/sh_pacoutfit.lua
- gamemode/items/base/sh_weapons.lua
- plugins/logging.lua
- plugins/pac.lua
- plugins/vendor/sh_plugin.lua
> Fix Iter loops

- gamemode/core/libs/sh_option.lua
The same as ix.config.SetDefault only for ix.option. Made to avoid editing core
> Add ix.option.SetDefault
